name = "MinHash"
uuid = "4b3c9753-2685-44e9-8a29-365b96c023ed"
authors = ["Jakob Nybo Nissen"]
version = "0.2.2"

[compat]
julia = "1"
DataStructures = "0.18"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[targets]
test = ["Test", "DataStructures"]
